### ISSUE TITLE
DistilTextEncoder fails with multiple targets

### ISSUE THREAD

**Issue by roquelopez** [uncharted-distil/distil-primitives#265]
Primitive `d3m.primitives.data_transformation.encoder.DistilTextEncoder` fails when there is more than one target.  Should I consider to use this primitive only when there is a single target or should it choose randomly a target instead of failing?

```
Traceback (most recent call last):
RuntimeError: Traceback (most recent call last):
  File "/src/d3m/d3m/runtime.py", line 1114, in _do_run_step
    self._run_step(step)
  File "/src/d3m/d3m/runtime.py", line 1104, in _run_step
    self._run_primitive(step)
  File "/src/d3m/d3m/runtime.py", line 979, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.fit_multi_produce, fit_multi_produce_arguments)
  File "/src/d3m/d3m/runtime.py", line 1080, in _call_primitive_method
    raise error
  File "/src/d3m/d3m/runtime.py", line 1076, in _call_primitive_method
    result = method(**arguments)
  File "/src/d3m/d3m/primitive_interfaces/base.py", line 534, in fit_multi_produce
    return self._fit_multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs, outputs=outputs)
  File "/src/d3m/d3m/primitive_interfaces/base.py", line 550, in _fit_multi_produce
    self.set_training_data(**arguments)
  File "/src/distil-primitives/distil/primitives/text_encoder.py", line 123, in set_training_data
    self._outputs = pd.Series(outputs)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/series.py", line 202, in __init__
    if is_empty_data(data) and dtype is None:
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/construction.py", line 586, in is_empty_data
    is_simple_empty = is_list_like_without_dtype and not data
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 1479, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by cdbethune** [comment]
Easy enough change to make it random, but does that actually produce a solution that is useful to you?

**Comment by roquelopez** [comment]
I think so. Perhaps it can use the first target. Thanks!
