### ISSUE TITLE
BERT classification scoring lower than expected

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-primitives#65]
In the eval we ended up with a score of ~0.05 for the wiki_qa problem, which is the one that uses the BERT classification primitive.  This should be almost exactly the same as the Exline score of 0.514507.

**Comment by cdbethune** [comment]
I re-tested locally with a batch size of 16 today (32 surpasses VRAM) and got the following exception:
```
Traceback (most recent call last):
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 941, in _do_run_step
    self._run_step(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 931, in _run_step
    self._run_primitive(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 839, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.fit_multi_produce, fit_multi_produce_arguments)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 914, in _call_primitive_method
    raise error
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 910, in _call_primitive_method
    result = method(**arguments)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 529, in fit_multi_produce
    return self._fit_multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs, outputs=outputs)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 565, in _fit_multi_produce
    produce_results = self._multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, **kwargs)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 461, in _multi_produce
    results.append(getattr(self, method_name)(timeout=timeout, iterations=iterations, **arguments))
  File "/home/chris/dev/git_work/distil-primitives/distil/primitives/bert_classification.py", line 165, in produce
  File "/home/chris/dev/git_work/distil-primitives/distil/modeling/bert_models.py", line 255, in predict
    num_workers=4,
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 771, in _get_data
    success, data = self._try_get_data()
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 161, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chris/dev/git_work/d3m/d3m/__main__.py", line 6, in <module>
    cli.main(sys.argv)
  File "/home/chris/dev/git_work/d3m/d3m/cli.py", line 1106, in main
    handler(arguments, parser)
  File "/home/chris/dev/git_work/d3m/d3m/cli.py", line 1021, in handler
    problem_resolver=problem_resolver,
  File "/home/chris/dev/git_work/d3m/d3m/cli.py", line 511, in runtime_handler
    problem_resolver=problem_resolver,
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 2531, in fit_score_handler
    fit_result.check_success()
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 68, in check_success
    raise self.error
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 972, in _run
    self._do_run()
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 958, in _do_run
    self._do_run_step(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 950, in _do_run_step
    ) from error
d3m.exceptions.StepFailedError: Step 5 for pipeline e3ef0538-675e-4e2e-ac23-5be74daabb0b failed.
```
Not sure if this is something to do with the batch size change.

**Comment by cdbethune** [comment]
Above exception occurs due to the file limit being set too low by default on Ubuntu.  Upping to max (65535) fixes the issue.
