### ISSUE TITLE
Audio transfer fails in featurize step

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-primitives#72]
The audio classification pipeline is currently failing in the `pretrained_audio` module:

```

ERROR:redirect:[Parallel(n_jobs=32)]: Using backend MultiprocessingBackend with 32 concurrent workers.
Traceback (most recent call last):
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 941, in _do_run_step
    self._run_step(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 931, in _run_step
    self._run_primitive(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 839, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.fit_multi_produce, fit_multi_produce_arguments)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 914, in _call_primitive_method
    raise error
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 910, in _call_primitive_method
    result = method(**arguments)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/unsupervised_learning.py", line 49, in fit_multi_produce
    return self._fit_multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 565, in _fit_multi_produce
    produce_results = self._multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, **kwargs)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 461, in _multi_produce
    results.append(getattr(self, method_name)(timeout=timeout, iterations=iterations, **arguments))
  File "/home/chris/dev/git_work/distil-primitives/distil/primitives/audio_transfer.py", line 135, in produce
    outputs = self._transform_inputs(inputs)
  File "/home/chris/dev/git_work/distil-primitives/distil/primitives/audio_transfer.py", line 122, in _transform_inputs
    feats = self.audio_set._featurize(inputs.audio)
  File "/home/chris/dev/git_work/distil-primitives/distil/modeling/pretrained_audio.py", line 70, in _featurize
    mel_feats = Parallel(n_jobs=32, backend='multiprocessing', verbose=10)(jobs)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/parallel.py", line 1016, in __call__
    self.retrieve()
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/parallel.py", line 908, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/pool.py", line 158, in send
    CustomizablePickler(buffer, self._reducers).dump(obj)
_pickle.PicklingError: Can't pickle <function audioarray2mel at 0x7f144f7ac048>: it's not the same object as distil.modeling.pretrained_audio.audioarray2mel
```

**Comment by cdbethune** [comment]
After updates to the loader and transfer primitives, I was getting the following when running the audio test pipeline in `auto-ml/pipelines`:

```
ERROR:redirect:[Parallel(n_jobs=64)]: Done 1224 tasks      | elapsed:  5.7min
ERROR:redirect:[Parallel(n_jobs=64)]: Done 1277 tasks      | elapsed:  6.0min
ERROR:redirect:[Parallel(n_jobs=64)]: Done 1330 tasks      | elapsed:  6.2min
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/chris/dev/git_work/distil-primitives/distil/primitives/audio_loader.py", line 74, in convert_load_file
    start = int(info.frames * (start / info.duration))
ZeroDivisionError: float division by zero
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 941, in _do_run_step
    self._run_step(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 931, in _run_step
    self._run_primitive(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 839, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.fit_multi_produce, fit_multi_produce_arguments)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 914, in _call_primitive_method
    raise error
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 910, in _call_primitive_method
    result = method(**arguments)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/transformer.py", line 72, in fit_multi_produce
    return self._fit_multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 565, in _fit_multi_produce
    produce_results = self._multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, **kwargs)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 461, in _multi_produce
    results.append(getattr(self, method_name)(timeout=timeout, iterations=iterations, **arguments))
  File "/home/chris/dev/git_work/distil-primitives/distil/primitives/audio_loader.py", line 184, in produce_collection
    outputs = self._audio_load(file_paths)
  File "/home/chris/dev/git_work/distil-primitives/distil/primitives/audio_loader.py", line 214, in _audio_load
    files_out = Parallel(n_jobs=64, backend='loky', verbose=10)(jobs)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ZeroDivisionError: float division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chris/dev/git_work/d3m/d3m/__main__.py", line 6, in <module>
    cli.main(sys.argv)
  File "/home/chris/dev/git_work/d3m/d3m/cli.py", line 1106, in main
    handler(arguments, parser)
  File "/home/chris/dev/git_work/d3m/d3m/cli.py", line 1021, in handler
    problem_resolver=problem_resolver,
  File "/home/chris/dev/git_work/d3m/d3m/cli.py", line 511, in runtime_handler
    problem_resolver=problem_resolver,
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 2531, in fit_score_handler
    fit_result.check_success()
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 68, in check_success
    raise self.error
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 972, in _run
    self._do_run()
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 958, in _do_run
    self._do_run_step(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 950, in _do_run_step
    ) from error
d3m.exceptions.StepFailedError: Step 0 for pipeline 650d7784-14c0-42e5-977e-59a3525d4c08 failed.
```

**Comment by cdbethune** [comment]
Above issues are now fixed, but the primitive now seems to be running out of RAM when tested on workstations.  Need to re-test on cluster.
