### ISSUE TITLE
default text encoder strategy selection

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-primitives#83]
The default strategy for the text encoder should be SVC to ensure consistent behavior with older versions of the primitive.  The sparseness of the created TFIDF matrix leads to a very different model fit time when run in that mode, which is now the default.

**Comment by cdbethune** [comment]
It also looks like running in SVC mode leads to the following:

```
DEBUG - 2020-01-02 20:37:51,157 - v-master-f352af4 - distil.primitives.text_encoder - Producing distil.primitives.text_encoder
WARNING - 2020-01-02 20:37:51,239 - v-master-f352af4 - distil - Exception running task ID b45841ae-e764-4f55-8bf6-0be66819006c: Step 15 for pipeline  failed.
Traceback (most recent call last):
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 941, in _do_run_step
    self._run_step(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 931, in _run_step
    self._run_primitive(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 839, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.fit_multi_produce, fit_multi_produce_arguments)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 914, in _call_primitive_method
    raise error
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 910, in _call_primitive_method
    result = method(**arguments)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 529, in fit_multi_produce
    return self._fit_multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs, outputs=outputs)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 565, in _fit_multi_produce
    produce_results = self._multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, **kwargs)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 461, in _multi_produce
    results.append(getattr(self, method_name)(timeout=timeout, iterations=iterations, **arguments))
  File "/home/chris/dev/git_work/distil-primitives/distil/primitives/text_encoder.py", line 137, in produce
    result = self._encoders[i].transform(text_inputs)
  File "/home/chris/dev/git_work/distil-primitives/distil/preprocessing/transformers.py", line 60, in transform
    out = self._model.decision_function(Xv)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/sklearn/linear_model/base.py", line 263, in decision_function
    "yet" % {'name': type(self).__name__})
sklearn.exceptions.NotFittedError: This LinearSVC instance is not fitted yet
```

**Comment by BalazsHoranyi** [comment]
Ok, My thought for using TFIDF without a classifier on top, was to allow the encoder to play nice with classification or regression problems, and other odd one-off texts. I agree TFIDF is a poor choice due to sparseness, but we need to play nice with regression problems as well. 
I think either have the encoder decide whether to do classification or regression based on the metadata or run PCA on top of the TFIDF to reduce sparseness. 
What dataset was the above stack trace from?
